#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l vmem=16gb
#PBS -l walltime=10:00:00

export SINGULARITYENV_OMP_NUM_THREADS=7

set -e
set -x

singularity exec -e docker://brainlife/validator-neuro-track:1.0 ./main.py

echo "done"
